### ISSUE TITLE
GIF demonstration is too rapid and the screen is too small to read anything

### ISSUE THREAD

**Issue by Navis-Raven** [chfw/yehua#5]
Hi, how are you ?

The GIF demonstration you made ? is too rapid and the screen is too small to read anything.

https://github.com/chfw/yehua

Maybe you should add also some introduction or explanation text to explain what this python package is used for.

Another question: what is the name of the movie on the gif ?

**Comment by chfw** [comment]
In order to make it slow, I have to remove the background so as to get a small gif. 

The name is Eternal Love, a Chinese drama. You can get it from youtube with English subtitles. I asked my wife for a name when writing this utility. Back then we had been watching the drama, so she then said how about `yehua`.

**Comment by Navis-Raven** [comment]
Good work ! 

Just need to add the Introduction, ie. a brief description of what is yehua software. There is all explanation of how we use it, but there is no text to describe or explain what is it, in brief phrase.
